# create post endpoint
POST http://localhost:7231/posts
content-type: application/json

{
    "authorId": 1,
    "title": "Javascript to the world",
    "postType": "page",
    "slug": "worlddd",
    "status": "published",
    "content": "Javascript is going to take over the world!",
    "schema": "{\r\n \"@context\": \"https:\/\/schema.org\", \r\n \"@type\": \"Person\"\r\n}",
    "featuredImageUrl": "https://images.app.goo.gl/2twFaFy51iKBmi519",
    "publishedOn": "2024-03-16T12:00:00+0000",
    "tags": [2],
    "metaOptions" : {
        "metaValue": "{\"sidebarEnabled\": false, \"footerEnabled\": false}"
    }
}

###

PATCH http://localhost:7231/posts
content-type: application/json

{
    "id": 4,
    "tags": [2]
}

GET http://localhost:7231/posts
content-type: application/json

DELETE http://localhost:7231/posts?id=4
content-type: application/json
