### /id
PATCH http://localhost:7231/users/
content-type: application/json

{
  "email": "john@doe.com",
  "password": "nestjsIS6@awesome"
}

# Get User (id)
GET http://localhost:7231/users/
content-type: application/json

#create user 
POST http://localhost:7231/users/
content-type: application/json

{
  "firstName": "Joe",
  "lastName": "Doe",
  "email": "oojoseph67@gmail.com",
  "password": "nestjsIS6@awesome"
}

POST http://localhost:7231/users/create-many
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImVtYWlsIjoiamFtZXNAZG9lLmNvbSIsImlhdCI6MTczNTY0OTY3MiwiZXhwIjoxNzM1NjUzMjcyLCJhdWQiOiJsb2NhbGhvc3Q6NzIzMSIsImlzcyI6ImxvY2FsaG9zdDo3MjMxIn0.weZQKuoEkG0uaaahKUY3tiREfdItliut5F7Ss6mkH1s

{
  "users": [
    {
      "firstName": "Mark",
      "lastName": "Doe",
      "email": "mark@doe.com",
      "password": "nestjsIS6@awesome"
  },
  {
      "firstName": "Jane",
      "lastName": "Doe",
      "email": "jane@doe.com",
      "password": "nestjsIS6@awesome"
   }
  ]
}
