### Signup
POST http://localhost:7231/users/auth/signup
content-type: application/json

{
  "email": "testV2@test.com",
  "password": "nestjsIS6@awesome"
}

### Signin
POST http://localhost:7231/users/auth/signin
content-type: application/json

{
  "email": "test@test.com",
  "password": "nestjsIS6@awesome"
}

### Who Am I
GET http://localhost:7231/users/auth/whoami
content-type: application/json

### Signout
POST http://localhost:7231/users/auth/signout
content-type: application/json
