POST http://localhost:7231/tags
content-type: application/json

{
    "name": "JAVASCRIPT",
    "description": "A post about javascript",
    "slug": "js",
    "featuredImageUrl": "https://example.com/image.jpg"
}

# ## delete
# DELETE http://localhost:7231/tags?id=2
# content-type: application/json

## soft delete
DELETE http://localhost:7231/tags/soft-delete?id=1
content-type: application/json
